TOPICS = {
    "spor": [
        "En sevdiğin spor dalı nedir ve neden bu kadar ilgi çekici buluyorsun?",
        "Son zamanlarda izlediğin veya takip ettiğin bir spor etkinliği var mıydı? Nasıldı?",
        "Futbol mu, basketbol mu, yoksa bireysel sporlar mı daha çok ilgini çekiyor? Neden?",
        "Sence sporun insan sağlığı ve toplum üzerindeki faydaları nelerdir? Birkaç örnek verebilir misin?",
        "E-spor hakkında ne düşünüyorsun? Geleneksel sporlarla aynı kategoride değerlendirilmeli mi?",
        "Bir sporcu olsaydın, hangi dalda başarılı olmak isterdin ve hedefin ne olurdu?",
        "Sporun fair-play ruhu neden önemlidir? Bu konuda bir örnek verebilir misin?",
        "Olimpiyat Oyunları'nın önemi nedir? Tarihinden ilginç bir detayı paylaşır mısın?",
        "Hangi spor dalında kuralların değiştirilmesi gerektiğini düşünüyorsun ve neden?",
        "Spor yapmanın en keyifli yanı nedir senin için?",
        "Takım sporları mı, bireysel sporlar mı daha çok sana hitap ediyor? Açıklar mısın?",
        "Bir antrenman rutini tasarlaman istenseydi, hangi egzersizleri dahil ederdin?",
        "Spora yeni başlayan birine ne gibi tavsiyelerde bulunursun?",
        "En unutulmaz spor anın veya maçın neydi?",
        "Dopingin spora etkileri hakkında ne düşünüyorsun? Spor etiğini nasıl etkiliyor?"
    ],
    "sanat": [
        "Son okuduğun kitap neydi? Seni en çok etkileyen yönü ne oldu?",
        "En sevdiğin ressam veya heykeltıraş kimdir? Eserlerinden birini anlatır mısın?",
        "Tiyatro mu, sinema mı daha çok ilgini çekiyor? Bu iki sanat dalının farkları nelerdir?",
        "Sanatın toplumdaki rolü hakkında ne düşünüyorsun? İnsanları nasıl etkiler?",
        "Bir müzik türü seçsen, hangisi olurdu ve neden o tür sana iyi geliyor?",
        "Dans sence bir sanat mıdır? Dansın kültürel önemi hakkında ne söyleyebilirsin?",
        "Fotoğrafçılık yeteneğin olsaydı, ne tür kareler çekmek isterdin?",
        "Görmek istediğin bir sanat eseri veya katılmak istediğin bir sanat etkinliği var mı? Anlatır mısın?",
        "Edebiyatın insan hayatındaki yeri nedir? Hangi edebi akım seni daha çok etkiliyor?",
        "Sanat ve teknoloji nasıl bir araya gelebilir? Örnekler verebilir misin?",
        "Bir film sahnesi tasarlasan, nasıl bir atmosfer yaratırdın ve hangi duyguyu vermek isterdin?",
        "Şiirin günümüzdeki önemi hakkında ne düşünüyorsun?",
        "En sevdiğin müzik enstrümanı hangisi ve neden?",
        "Modern sanat hakkında ne söyleyebilirsin? Anlaşılması zor mudur?",
        "Sanatçının toplumdaki sorumluluğu nedir sence?"
    ],
    "bilim": [
        "Evrenin gizemleri hakkında seni en çok şaşırtan bilgi nedir?",
        "Yapay zeka geleceğimizi nasıl etkileyecek? Potansiyel faydaları ve riskleri nelerdir?",
        "Hangi bilimsel keşif seni en çok etkiledi ve neden? Bu keşif hayatımızı nasıl değiştirdi?",
        "Sence uzaylılar var mı? Evrende yalnız mıyız, yoksa başka yaşam formları da mevcut mu?",
        "İnsanlığın gelecekteki en büyük bilimsel hedefi ne olmalı ve neden?",
        "Büyük Veri (Big Data) nedir ve modern dünyada neden bu kadar önemlidir?",
        "Kuantum bilgisayarlar gelecekte ne gibi yenilikler getirecek? Sıradan kullanıcıları nasıl etkiler?",
        "Genetik mühendisliği hakkında ne düşünüyorsun? Etiği ve potansiyeli nedir?",
        "İklim değişikliği ile mücadelede bilimin rolü nedir? Hangi çözümler umut vadediyor?",
        "İnsan beyni hakkında en ilginç bulduğun şey nedir? Bilim bu konuda nereye gidiyor?",
        "Sürdürülebilir enerji kaynakları hakkında neler biliyorsun? Hangisi daha umut verici?",
        "Aşılar nasıl çalışır ve toplum sağlığı için neden kritiktir?",
        "Bir bilim insanı olsan, hangi alanda araştırma yapmak isterdin ve neden?",
        "Robot teknolojisi hayatımızı nasıl kolaylaştıracak ya da zorlaştıracak?",
        "Bilimsel yöntemin temel prensipleri nelerdir ve neden önemlidir?"
    ],
    "kişilik": [
        "Hayatta seni motive eden şeyler nelerdir? Seni harekete geçiren ana faktörler nelerdir?",
        "Kendini üç kelimeyle nasıl tanımlarsın ve neden bu kelimeleri seçtin?",
        "Gelecekte nasıl bir insan olmak istersin? Hedeflerin ve hayallerin nelerdir?",
        "Başarı senin için ne anlama geliyor? Başarıyı nasıl ölçersin?",
        "Stresli durumlarla başa çıkmak için kullandığın yöntemler nelerdir?",
        "En büyük korkun nedir ve bu korkunla nasıl başa çıkmaya çalışıyorsun?",
        "Seni en çok güldüren veya eğlendiren şey nedir?",
        "Hangi özelliğini değiştirmek isterdin ve neden?",
        "Bir süper gücün olsaydı, hangisi olurdu ve onu nasıl kullanırdın?",
        "Hayatta sana ilham veren biri var mı? Kim ve neden?",
        "Karar verirken mantığını mı, duygularını mı daha çok kullanırsın?",
        "Bir günü dolu dolu yaşamak senin için ne anlama geliyor?",
        "En çok neye değer verirsin?",
        "Hayattaki en büyük öğrenimin ne oldu?",
        "Hangi konuda kendini geliştirmek istersin?"
    ],
    "günlük hayat": [
        "Bugün nasıl geçti? Özellikle ilginç veya farklı bir şey oldu mu?",
        "Hafta sonu planların neler? Boş zamanını genellikle nasıl değerlendirirsin?",
        "Şu an ne yapıyorsun? Yoğun bir gün mü geçirdin?",
        "En sevdiğin yemek nedir? Kendi tarifin var mı?",
        "Günde kaç fincan kahve veya çay içersin? Favori içeceğin nedir?",
        "Ev işleri arasında en çok neyi yapmaktan hoşlanırsın, en çok neyi yapmaktan nefret edersin?",
        "Sence mutlu bir günlük hayatın sırrı nedir?",
        "Sabah rutinlerin var mı? Güne nasıl başlarsın?",
        "Akşamları genellikle ne yaparsın? Hobilerin var mı?",
        "Ulaşım için hangi yöntemleri tercih edersin? Toplu taşıma mı, özel araç mı?",
        "Sence modern hayatın en büyük zorlukları nelerdir?",
        "Bir haftalık tatil planlasaydın, nereye giderdin ve ne yapardın?",
        "En sevdiğin film veya dizi hangisi ve neden?",
        "Yeni bir dil öğrenmek ister miydin? Hangi dili ve neden?",
        "Bugünlerde seni en çok meşgul eden düşünce ne?"
    ],
    "teknoloji": [
        "Yeni çıkan telefonlar veya teknolojik cihazlar hakkında ne düşünüyorsun? Takip ediyor musun?",
        "Akıllı ev teknolojileri hayatımızı kolaylaştırıyor mu sence? Örnekler verebilir misin?",
        "Büyük veri nedir ve neden önemlidir? Günlük hayatımızdaki örnekleri nelerdir?",
        "Kuantum bilgisayarlar gelecekte ne gibi yenilikler getirecek? Bizi nasıl etkiler?",
        "Siber güvenlik neden bu kadar önemli hale geldi? Kendimizi nasıl koruyabiliriz?",
        "Yazılım geliştirme hakkında ne biliyorsun? Hangi programlama dilleri ilgini çekiyor?",
        "Sosyal medyanın faydaları ve zararları hakkında ne düşünüyorsun?",
        "Giyilebilir teknoloji (akıllı saatler, bileklikler vb.) hakkında ne söyleyebilirsin?",
        "Blockchain teknolojisi nedir ve geleceği hakkında ne öngörüyorsun?",
        "Robotların günlük hayatımızdaki yeri ne olacak sence? İşlerimizi ele geçirecekler mi?",
        "Bulut bilişimin avantajları ve dezavantajları nelerdir?",
        "Nesnelerin İnterneti (IoT) kavramı hayatımızı nasıl değiştirecek?",
        "Artırılmış gerçeklik (AR) ve sanal gerçeklik (VR) teknolojileri hakkında ne düşünüyorsun?",
        "Teknolojinin eğitimdeki rolü nedir? Öğrenme süreçlerini nasıl dönüştürüyor?",
        "Gelecekte bizi bekleyen en heyecan verici teknolojik gelişme sence ne?"
    ],
    "tarih": [
        "Geçmiş medeniyetlerden en çok ilgini çeken hangisi ve neden?",
        "Tarihten hangi olayı değiştirmek isterdin ve bu değişikliğin sonuçları ne olurdu?",
        "Osmanlı İmparatorluğu hakkında ne biliyorsun? Seni en çok etkileyen dönem veya padişah hangisi?",
        "İnsanlık tarihindeki en önemli buluş sence nedir ve neden?",
        "Bir zaman makinen olsaydı, tarihin hangi dönemine giderdin ve ne yapardın?",
        "Antik Roma İmparatorluğu'nun yükseliş ve düşüş nedenleri hakkında ne düşünüyorsun?",
        "İkinci Dünya Savaşı'nın en belirleyici anı sence neydi?",
        "Tarihteki en büyük lider kimdir senin için ve neden?",
        "Sanayi Devrimi'nin dünyayı nasıl değiştirdiğini anlatır mısın?",
        "Feodalizm nedir ve orta çağ Avrupa'sındaki etkileri nelerdi?",
        "Bir antik uygarlığı ziyaret etsen, hangisi olurdu ve ne görmek isterdin?",
        "Tarihin tekerrür ettiğine inanıyor musun? Nedenleriyle açıklar mısın?",
        "Rönesans dönemi sanat ve bilimde ne gibi devrimler yarattı?",
        "Büyük Göçler veya Kavimler Göçü'nün Avrupa tarihi üzerindeki etkileri nelerdi?",
        "Tarihi olayları öğrenmek neden önemlidir? Geçmişten ders çıkarabilir miyiz?"
    ]
}